// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxjbrqkelzzjljlmeujh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4amJycWtlbHp6amxqbG1ldWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTYyNDksImV4cCI6MjA3MzE5MjI0OX0.qiJPsPFUBgnBXjDW6Av1hSnDVB-RaVWQhvMZzMErygc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});